/**
  The InternalFrame package provides classes deleting and editing data in the database.
  This includes classes for defining table structures, querying and modifying data in tables.
 */
package InternalFrames;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
  The DeleteCustomer class represents a graphical user interface for deleting Customer data from the database.
  It extends the javax.swing.JFrame class to create a window for displaying the data.
  This class includes methods for selecting and deleting customer data from the database.
  <p>This class is designed to be used in conjunction with a database system that customer data.</p>
  @author woola
 */
public final class DeleteCustomer extends javax.swing.JInternalFrame {
    /**
     Declaring connection Variable
     */
    Connection con;
    /**
     Declaring Prepared statement Variable
     */
    PreparedStatement statement;
    /**
     Declaring statement Variable
     */
    Statement st;
    /**
     Declaring local host Variable
     */
    String cs;
    /**
     Declaring connection user Variable
     */
    String user;
    /**
     Declaring connection password Variable
     */
    String password;
    /**
     Declaring MySQL query Variable
     */
    String query;
    /**
     Declaring result Variable
     */
    ResultSet rs;
    /**
     Declaring count Variable
     */
    int count = 0;
    /**
     * Creates new form AddSupplier
     */
    public DeleteCustomer() {
        // Initializing the user interface components:
        initComponents();
        setLocation(120,40);
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/inventorydatabase";
        user = "root";
        password = "";
        setLocation(120,40);
        AddDataToCustomerName();
    }
    /**
      This method selects customer name from the database and adds it to the district comboBox
     */
    public void AddDataToCustomerName(){
        // Connect to the database and execute a query to add suppliers:
        try {
            Class.forName("com.mysql.jdbc.Driver"); //register the driver
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT Name FROM customer";
            st = con.createStatement();           
            statement = con.prepareStatement(query);
            rs = st.executeQuery(query);
             // Iterate over the result set and add items to the comboBox
            while(rs.next()){
                boxdelete.addItem(rs.getString("Name"));   
            }
             boxdelete.setSelectedItem(null);
             txtname.setText(null);
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                con.close();
                statement.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        boxdelete = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Delete Customers");

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(51, 0, 255));
        lbltitle.setText("Select Customer Name To Delete");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        btndelete.setBackground(java.awt.Color.red);
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setToolTipText("click to delete customer");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        boxdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btndelete)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(boxdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btndelete)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
      Handles the event when the "delete" button is clicked.
      <p>This method is called when the user clicks the "delete" button in the user interface.
      It deletes a record of the customer from the database.</p>
      @param evt the ActionEvent object represent the event that will occur
     */
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        //Connect to the database and execute a query to to delete a record in customer table.
        try{
            Class.forName("com.mysql.jdbc.Driver"); //register the driver
            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
            query = "delete from customer where Name ='"+txtname.getText()+"'";
            int success = st.executeUpdate(query);
            if(success == 1){
                JOptionPane.showMessageDialog(null, "Customer Deleted Succefully.");
            }
            else{
                JOptionPane.showMessageDialog(null, "The customer could not be found");
            }
            txtname.setText("");
        }
        catch (SQLException | ClassNotFoundException ex){
        }
        finally{
            try {
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed
    /**
      Handles the selection of an item in the JComboBox.
      @param evt is the ActionEvent object that trigger this method
     */
    private void boxdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdeleteActionPerformed
        //seting the data in the comboBox to the product name texField:
        txtname.setText((String) boxdelete.getSelectedItem());
    }//GEN-LAST:event_boxdeleteActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxdelete;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
