/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrames;
import Logins.LoginPage;
import Tables.Customer_Table;
import Tables.Products_Table;
import Tables.Sales_Table;
import Tables.Supplier_Table;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author woola
 */
public class Menu extends javax.swing.JFrame {
    /**
     Declaring the static final String variable RESULT and assigning it a value CUSTOMERINFORMATION
     */
    public static final String RESULT = "CUSTOMERINFORMATION.pdf";
     /**
     Declaring connection Variable
     */
    Connection con;
    /**
     Declaring Prepared statement Variable
     */
    PreparedStatement statement;
    /**
     Declaring statement Variable
     */
    Statement st;
    /**
     Declaring local host Variable
     */
    String cs;
    /**
     Declaring connection user Variable
     */
    String user;
    /**
     Declaring connection password Variable
     */
    String password;
    /**
     Declaring MySQL query Variable
     */
    String query;
    /**
     Declaring result Variable
     */
    ResultSet rs;
    /**
     Declaring count Variable
     */
    int count = 0;
    /**
     * Creates new form Menu
     */
    public Menu() {
       con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/inventorydatabase";
        user = "root";
        password = "";
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        order = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        storelbl = new javax.swing.JLabel();
        storepiclbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        taskpanel = new javax.swing.JMenuBar();
        Menumenu = new javax.swing.JMenu();
        productmenu = new javax.swing.JMenuItem();
        customermenu = new javax.swing.JMenuItem();
        suppliermenu = new javax.swing.JMenuItem();
        salemenu = new javax.swing.JMenuItem();
        reportmenu = new javax.swing.JMenu();
        salesmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setBackground(java.awt.Color.red);
        btnlogout.setText("Logout");
        btnlogout.setToolTipText("Click to log out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrames/Img2.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 240, 190));

        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrames/Picture6.png"))); // NOI18N
        order.setToolTipText("Click Here to Add,Delete,Update,Search Orders");
        order.setMaximumSize(new java.awt.Dimension(128, 128));
        order.setMinimumSize(new java.awt.Dimension(128, 128));
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        getContentPane().add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.green);
        jLabel3.setText("Sales");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, -1));

        storelbl.setBackground(java.awt.Color.red);
        storelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        storelbl.setForeground(java.awt.Color.green);
        storelbl.setText("Store");
        getContentPane().add(storelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, -1));

        storepiclbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrames/Picture8.png"))); // NOI18N
        getContentPane().add(storepiclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrames/img3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 360));

        Menumenu.setText("MENU");

        productmenu.setText("Product List");
        productmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productmenuActionPerformed(evt);
            }
        });
        Menumenu.add(productmenu);

        customermenu.setText("Customer List");
        customermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customermenuActionPerformed(evt);
            }
        });
        Menumenu.add(customermenu);

        suppliermenu.setText("Suppliers");
        suppliermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliermenuActionPerformed(evt);
            }
        });
        Menumenu.add(suppliermenu);

        salemenu.setText("Sales");
        salemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salemenuActionPerformed(evt);
            }
        });
        Menumenu.add(salemenu);

        taskpanel.add(Menumenu);

        reportmenu.setText("Report");

        salesmenu.setText("Sales Report");
        salesmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesmenuActionPerformed(evt);
            }
        });
        reportmenu.add(salesmenu);

        taskpanel.add(reportmenu);

        setJMenuBar(taskpanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productmenuActionPerformed
        // TODO add your handling code here:
        Products_Table products_table = new Products_Table();
        products_table.show();
        dispose();  
    }//GEN-LAST:event_productmenuActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed

        LoginPage loginpage = new LoginPage();
        loginpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void customermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customermenuActionPerformed
        // TODO add your handling code here:
        Customer_Table customer_table = new Customer_Table();
        customer_table.show();
        dispose();
    }//GEN-LAST:event_customermenuActionPerformed

    private void suppliermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliermenuActionPerformed
        // TODO add your handling code here:
        Supplier_Table supplier_table = new Supplier_Table();
        supplier_table.show();
        dispose();
    }//GEN-LAST:event_suppliermenuActionPerformed

    private void salemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salemenuActionPerformed
        // TODO add your handling code here:
        Sales_Table sales_table = new Sales_Table();
        sales_table.show();
        dispose();
    }//GEN-LAST:event_salemenuActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
         Sales_Table sales_table = new Sales_Table();
        sales_table.show();
        dispose();
    }//GEN-LAST:event_orderActionPerformed

    private void salesmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesmenuActionPerformed
        // step 1
        Document document = new Document(PageSize.A5.rotate());
            try {
                // step 2
                PdfWriter.getInstance(document, new FileOutputStream(RESULT));
            } catch (FileNotFoundException | DocumentException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        // step 3
        //opening  the document
        document.open();
        // step 4
        PdfPTable table = new PdfPTable(4);
        try{
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/inventorydatabase";
        user = "root";
        password = "";
            Class.forName("com.mysql.jdbc.Driver"); //register the driver
            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
            query = "select * from customer";//exwcute 
             rs = st.executeQuery(query);
            while(rs.next()){    
                table.addCell(rs.getString("Name"));
                table.addCell(rs.getString("Mobile"));
                table.addCell(rs.getString("District"));
                table.addCell(rs.getString("Address"));
            }
            document.add(table);
         }
            catch(ClassNotFoundException ex){
            } catch (SQLException | DocumentException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        //opening the file
        if(Desktop.isDesktopSupported()){
        try{
            File myfile = new File("CUSTOMERINFORMATION.pdf");
            Desktop.getDesktop().open(myfile);
        }catch(IOException ex){
        }
        // step 5
        document.close();
        }  
    }//GEN-LAST:event_salesmenuActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menumenu;
    private javax.swing.JButton btnlogout;
    private javax.swing.JMenuItem customermenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton order;
    private javax.swing.JMenuItem productmenu;
    private javax.swing.JMenu reportmenu;
    private javax.swing.JMenuItem salemenu;
    private javax.swing.JMenuItem salesmenu;
    private javax.swing.JLabel storelbl;
    private javax.swing.JLabel storepiclbl;
    private javax.swing.JMenuItem suppliermenu;
    private javax.swing.JMenuBar taskpanel;
    // End of variables declaration//GEN-END:variables
}
